

------------------------------

SET CURRENT SCHEMA Z76164;

-- CREATE TABLESPACE 1 FOR USERS
CREATE TABLESPACE Z76164P1 IN Z76164
  USING STOGROUP ZXPUSER PRIQTY 20 SECQTY 20
  BUFFERPOOL BP0 CLOSE NO COMPRESS YES;
COMMIT;

-- CREATE USERS TABLE
CREATE TABLE Z76164.USERS
  (ACCT_NUM    CHAR(10)     NOT NULL,
   FNAME       CHAR(15)     NOT NULL,
   LNAME       CHAR(20)     NOT NULL,
   EMAIL       CHAR(30)     NOT NULL,
   PIN         CHAR(4)      NOT NULL,
   PRIMARY KEY(ACCT_NUM))
  IN Z76164.Z76164P1;
COMMIT;

-- CREATE INDEX
CREATE UNIQUE INDEX Z76164.USERSI
ON Z76164.USERS (ACCT_NUM ASC)
USING STOGROUP ZXPUSER PRIQTY 12
BUFFERPOOL BP0 CLOSE NO;
COMMIT;

-- CREATE TABLESPACE 2 FOR WALLET
CREATE TABLESPACE Z76164P2 IN Z76164
  USING STOGROUP ZXPUSER PRIQTY 20 SECQTY 20
  BUFFERPOOL BP0 CLOSE NO COMPRESS YES;
COMMIT;

-- CREATE WALLET TABLE
CREATE TABLE Z76164.WALLET
  (ACCT_NUM    CHAR(10)     NOT NULL,
   BALANCE     DECIMAL(10,2) NOT NULL,
   PRIMARY KEY(ACCT_NUM))
  IN Z76164.Z76164P2;
COMMIT;

-- CREATE INDEX
CREATE UNIQUE INDEX Z76164.WALLETI
ON Z76164.WALLET (ACCT_NUM ASC)
USING STOGROUP ZXPUSER PRIQTY 12
BUFFERPOOL BP0 CLOSE NO;
COMMIT;

-- CREATE TABLESPACE 3 FOR TRANSACTIONS
CREATE TABLESPACE Z76164P3 IN Z76164
  USING STOGROUP ZXPUSER PRIQTY 20 SECQTY 20
  BUFFERPOOL BP0 CLOSE NO COMPRESS YES;
COMMIT;

-- CREATE TRANSACTIONS TABLE
CREATE TABLE Z76164.TRANSACTIONS
  (ACCT_NUM    CHAR(10)     NOT NULL,
   TXN_TYPE    CHAR(3)      NOT NULL,
   AMOUNT      DECIMAL(10,2) NOT NULL,
   TXN_DATE    TIMESTAMP    NOT NULL,
   PRIMARY KEY(ACCT_NUM, TXN_DATE))
  IN Z76164.Z76164P3;
COMMIT;

-- CREATE INDEX
CREATE INDEX Z76164.TRANSACTIONI
ON Z76164.TRANSACTIONS (ACCT_NUM ASC, TXN_DATE DESC)
USING STOGROUP ZXPUSER PRIQTY 12
BUFFERPOOL BP0 CLOSE NO;
COMMIT;

-- VERIFY
SELECT NAME, CREATOR, DBNAME, TSNAME
FROM SYSIBM.SYSTABLES
WHERE CREATOR = 'Z76164';


SELECT * FROM Z76164.USERS;
SELECT * FROM Z76164.WALLET;
SELECT * FROM Z76164.TRANSACTIONS;

SELECT * FROM Z76164.USERS FETCH FIRST 1 ROW ONLY;
SELECT * FROM Z76164.WALLET FETCH FIRST 1 ROW ONLY;
SELECT * FROM Z76164.TRANSACTIONS FETCH FIRST 1 ROW ONLY;


-- INSERT USER 1
INSERT INTO Z76164.USERS (ACCT_NUM, FNAME, LNAME, EMAIL, PIN)
VALUES ('ACC0000002', 'PAVANKUMAR', 'GUPTA', 'pavan@gmail.com', '1111');

INSERT INTO Z76164.WALLET (ACCT_NUM, BALANCE)
VALUES ('ACC0000002', 1000.00);

-- INSERT USER 2
INSERT INTO Z76164.USERS (ACCT_NUM, FNAME, LNAME, EMAIL, PIN)
VALUES ('ACC0000003', 'DEEPAK', 'TALELE', 'deepak@gmail.com', '2222');

INSERT INTO Z76164.WALLET (ACCT_NUM, BALANCE)
VALUES ('ACC0000003', 1000.00);

COMMIT;


-- STEP 1: RECREATE TABLESPACE
CREATE TABLESPACE Z76164P3 IN Z76164
  USING STOGROUP ZXPUSER PRIQTY 20 SECQTY 20
  BUFFERPOOL BP0 CLOSE NO COMPRESS YES;
COMMIT;

-- STEP 2: RECREATE TABLE
CREATE TABLE Z76164.TRANSACTIONS
  (TXN_ID      INTEGER       NOT NULL GENERATED ALWAYS AS IDENTITY,
   ACCT_NUM    CHAR(10)      NOT NULL,
   TXN_TYPE    CHAR(3)       NOT NULL,
   AMOUNT      DECIMAL(10,2) NOT NULL,
   TXN_DATE    TIMESTAMP     NOT NULL,
   PRIMARY KEY(TXN_ID))
  IN Z76164.Z76164P3;
COMMIT;

-- STEP 3: RECREATE INDEX
CREATE INDEX Z76164.TRANSACTIONI
ON Z76164.TRANSACTIONS (ACCT_NUM ASC, TXN_DATE DESC)
USING STOGROUP ZXPUSER PRIQTY 12
BUFFERPOOL BP0 CLOSE NO;
COMMIT;


DROP TABLE Z76164.TRANSACTIONS;
COMMIT;

DROP TABLESPACE Z76164.Z76164P3;
COMMIT;

CREATE TABLESPACE Z76164P3 IN Z76164
  USING STOGROUP ZXPUSER PRIQTY 20 SECQTY 20
  BUFFERPOOL BP0 CLOSE NO COMPRESS YES;
COMMIT;

CREATE TABLE Z76164.TRANSACTIONS
  (ACCT_NUM    CHAR(10)      NOT NULL,
   TXN_TYPE    CHAR(3)       NOT NULL,
   AMOUNT      DECIMAL(10,2) NOT NULL,
   TXN_DATE    TIMESTAMP     NOT NULL)
  IN Z76164.Z76164P3;
COMMIT;

CREATE INDEX Z76164.TRANSACTIONI
ON Z76164.TRANSACTIONS (ACCT_NUM ASC, TXN_DATE DESC)
USING STOGROUP ZXPUSER PRIQTY 12
BUFFERPOOL BP0 CLOSE NO;
COMMIT;


SELECT COLNAME, COLTYPE, LENGTH, SCALE, NULLS 
FROM SYSCAT.COLUMNS 
WHERE TABNAME IN ('USERS', 'WALLET', 'TRANSACTIONS')
AND TABSCHEMA = 'Z76164'
ORDER BY TABNAME, COLNO;